// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydaTKvYtp76TCnBceWiRx-yt5Ggxgkhk',
    appId: '1:305889307562:web:c5478808b791f2ce6699d3',
    messagingSenderId: '305889307562',
    projectId: 'fct-connect-estudasses',
    authDomain: 'fct-connect-estudasses.firebaseapp.com',
    storageBucket: 'fct-connect-estudasses.appspot.com',
    measurementId: 'G-4Q9RZ187TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kEN-9K8yLRgCcM5T59lZ0l92NXs9q38',
    appId: '1:305889307562:android:a027a4f29368e8106699d3',
    messagingSenderId: '305889307562',
    projectId: 'fct-connect-estudasses',
    storageBucket: 'fct-connect-estudasses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0sbbG7ukalw39d3vW9vbBFtr8Kj3k-V4',
    appId: '1:305889307562:ios:c28bf2450e313ee46699d3',
    messagingSenderId: '305889307562',
    projectId: 'fct-connect-estudasses',
    storageBucket: 'fct-connect-estudasses.appspot.com',
    iosClientId: '305889307562-ksu3kiilfmbftnunptsf7hj4gl0lctv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fctconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0sbbG7ukalw39d3vW9vbBFtr8Kj3k-V4',
    appId: '1:305889307562:ios:c28bf2450e313ee46699d3',
    messagingSenderId: '305889307562',
    projectId: 'fct-connect-estudasses',
    storageBucket: 'fct-connect-estudasses.appspot.com',
    iosClientId: '305889307562-ksu3kiilfmbftnunptsf7hj4gl0lctv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fctconnect',
  );
}
