name: responsive_login_ui
description: Responsive SignUp & Login Screens

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+3
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  lottie: ^1.4.2
  http: ^0.13.1
  file_picker: ^5.0.2
  flutter_dropzone: ^3.0.5
  flutter_platform_widgets: ^3.3.2
  fluro: ^2.0.5
  intl: ^0.18.1
  cookie_jar: ^4.0.2
  dio_cookie_manager: ^3.0.0
  shared_preferences: ^2.0.6
  dio: ^5.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+9
  geolocator: ^9.0.0
  permission_handler: ^10.2.0
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  firebase_analytics: ^10.4.2
  go_router: ^7.1.1
  url_strategy: ^0.2.0
  syncfusion_flutter_calendar: ^21.2.9
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  animated_background: ^2.0.0
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.3.1
  video_player: ^2.6.1
  chewie: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/background.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
