name: responsive_login_ui
description: Responsive SignUp & Login Screens

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+3
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  lottie: ^1.4.2
  http: ^0.13.6
  file_picker: ^5.3.0
  flutter_dropzone: ^3.0.5
  flutter_platform_widgets: ^3.3.2
  fluro: ^2.0.5
  intl: ^0.17.0
  date_time_picker: ^2.0.1
  cookie_jar: ^4.0.2
  dio_cookie_manager: ^3.0.0
  shared_preferences: ^2.0.6
  dio: ^5.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+9
  geolocator: ^9.0.0
  permission_handler: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
